name: Node.js CI

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/**'
      - 'src/ci-cd-react/ClientApp/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./src/ci-cd-react/ClientApp
    - run: npm run build --if-present      
      working-directory: ./src/ci-cd-react/ClientApp
    - run: npm test
      working-directory: ./src/ci-cd-react/ClientApp
      env:        
        CI: true
